[build]
  base = "site"
  publish = "public"
  command = "npm ci && hugo build -e production"

[build.environment]
  HUGO_VERSION = "0.150.0"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_BASEURL = "https://CHANGEME/"

[context.deploy-preview]
  command = "hugo --enableGitInfo --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --enableGitInfo --buildFuture -b $DEPLOY_PRIME_URL"
