kind: Namespace
apiVersion: v1
metadata:
  name: agent-sandbox-system

---

kind: ServiceAccount
apiVersion: v1
metadata:
  name: agent-sandbox-controller
  namespace: agent-sandbox-system
  labels:
    app: agent-sandbox-controller

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: agent-sandbox-controller
subjects:
- kind: ServiceAccount
  name: agent-sandbox-controller
  namespace: agent-sandbox-system
roleRef:
  kind: ClusterRole
  name: agent-sandbox-controller
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: agent-sandbox-controller-extensions
subjects:
- kind: ServiceAccount
  name: agent-sandbox-controller
  namespace: agent-sandbox-system
roleRef:
  kind: ClusterRole
  name: agent-sandbox-controller-extensions
  apiGroup: rbac.authorization.k8s.io

---

kind: Service
apiVersion: v1
metadata:
  name: agent-sandbox-controller
  namespace: agent-sandbox-system
  labels:
    app: agent-sandbox-controller
spec:
  selector:
    app: agent-sandbox-controller
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP

---

kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: agent-sandbox-controller
  namespace: agent-sandbox-system
  labels:
    app: agent-sandbox-controller
spec:
  serviceName: agent-sandbox-controller
  replicas: 1
  selector:
    matchLabels:
      app: agent-sandbox-controller
  template:
    metadata:
      labels:
        app: agent-sandbox-controller
    spec:
      serviceAccountName: agent-sandbox-controller
      containers:
      - name: agent-sandbox-controller
        image: ko://sigs.k8s.io/agent-sandbox/cmd/agent-sandbox-controller # placeholder value, replaced by deployment scripts
        args:
          - "--extensions"
