apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

# This example adds the "kata" runtimeClassName to the Sandbox Pod spec
patches:
- path: patch-kata.yaml
  target:
    kind: Sandbox
    name: sandbox-example
